{
  <|"Slug" -> "tadpole", "Section" -> "5.1", "PaperType" -> "Top", "SymbolicStatus" -> "ok", "SymbolicSources" -> 6, "SymbolicMasters" -> 1, "PrimeFallback" -> False, "PrimeSources" -> 0, "PrimeMasters" -> 0, "Note" -> "Symbolic tables parsed successfully."|>,
  <|"Slug" -> "bubble_massive", "Section" -> "5.2", "PaperType" -> "TypeII", "SymbolicStatus" -> "ok", "SymbolicSources" -> 6, "SymbolicMasters" -> 3, "PrimeFallback" -> False, "PrimeSources" -> 0, "PrimeMasters" -> 0, "Note" -> "Symbolic tables parsed successfully."|>,
  <|"Slug" -> "hq_triangle_1loop", "Section" -> "5.3", "PaperType" -> "TypeII", "SymbolicStatus" -> "ok", "SymbolicSources" -> 6, "SymbolicMasters" -> 3, "PrimeFallback" -> False, "PrimeSources" -> 0, "PrimeMasters" -> 0, "Note" -> "Symbolic tables parsed successfully."|>,
  <|"Slug" -> "vacuum_2loop", "Section" -> "6.1", "PaperType" -> "TypeII", "SymbolicStatus" -> "ok", "SymbolicSources" -> 6, "SymbolicMasters" -> 4, "PrimeFallback" -> False, "PrimeSources" -> 0, "PrimeMasters" -> 0, "Note" -> "Symbolic tables parsed successfully."|>,
  <|"Slug" -> "vacuum_3loop", "Section" -> "6.1", "PaperType" -> "TypeII", "SymbolicStatus" -> "ok", "SymbolicSources" -> 6, "SymbolicMasters" -> 38, "PrimeFallback" -> False, "PrimeSources" -> 0, "PrimeMasters" -> 0, "Note" -> "Symbolic tables parsed successfully."|>,
  <|"Slug" -> "sunset_cut_vertical", "Section" -> "6.2", "PaperType" -> "TypeIII", "SymbolicStatus" -> "ok", "SymbolicSources" -> 6, "SymbolicMasters" -> 3, "PrimeFallback" -> False, "PrimeSources" -> 0, "PrimeMasters" -> 0, "Note" -> "Symbolic tables parsed successfully."|>,
  <|"Slug" -> "sunset_4prop", "Section" -> "6.3", "PaperType" -> "TypeI", "SymbolicStatus" -> "ok", "SymbolicSources" -> 6, "SymbolicMasters" -> 13, "PrimeFallback" -> False, "PrimeSources" -> 0, "PrimeMasters" -> 0, "Note" -> "Symbolic tables parsed successfully."|>,
  <|"Slug" -> "hq_potential_2loop", "Section" -> "6.4", "PaperType" -> "TypeIII-like", "SymbolicStatus" -> "ok", "SymbolicSources" -> 6, "SymbolicMasters" -> 29, "PrimeFallback" -> False, "PrimeSources" -> 0, "PrimeMasters" -> 0, "Note" -> "Symbolic tables parsed successfully."|>,
  <|"Slug" -> "self_energy_3loop_1ext", "Section" -> "6.4", "PaperType" -> "TypeI", "SymbolicStatus" -> "timeout", "SymbolicSources" -> 0, "SymbolicMasters" -> 0, "PrimeFallback" -> True, "PrimeSources" -> 6, "PrimeMasters" -> 408, "Note" -> "Symbolic FIRE timed out at 1200 s. Prime fallback is stored under prime_d13_m3_s5_p1/parsed/."|>
}
